@ATSourcing.Api_HostAddress = https://localhost:60368
@CandidateId = e3f31bc5-a601-42d6-b925-5e638e845bcd
@JobId = de2deca0-1252-45bd-b5f7-38518503f3a0
@JobApplicationId = 8b97c4e1-5831-4f9f-a2a2-69b4c44746ef

POST  https://localhost:53881/api/v1/candidates/
Accept: application/json
Content-Type: application/json

{
  "firstName": "Alan",
  "lastName": "Maia",
  "email": "maiaalan@gmail.com",
  "age": 25,
  "userId": "F03E6EB3-53F2-42B5-B13B-4A5F99C5FE74"
}

###

GET  https://localhost:53881/api/v1/candidates/{{CandidateId}}
Accept: application/json

###

GET  https://localhost:53881/api/v1/candidates?page=1&pageSize=6&sort=age&sortDirection=desc
Accept: application/json

###

Patch  https://localhost:53881/api/v1/candidates/{{CandidateId}}
Accept: application/json
Content-Type: application/json

{
  "age": 26,
  "lastName": "Oliveira Maia"
}

###

Delete  https://localhost:53881/api/v1/candidates/{{CandidateId}}
Accept: application/json

###

POST  https://localhost:53881/api/v1/jobs/
Accept: application/json
Content-Type: application/json

{
  "title": "Developer",
  "description": "Developer Job",
  "vacancyCount": 1,
  "applicationDeadline": "2025-03-01",
  "salaryRange": {
    "min": 50000,
    "max": 60000
  },
  "stepFlowDefinition": {
    "current": {
      "name": "Conversation",
      "description": "Conversation Step",
      "startingState": 0,
      "specificData": {
        "Question": "Why do you want to work at our company?"
      }
    },
    "next": {
      "current": {
        "name": "Conversation",
        "description": "Conversation Step",
        "startingState": 0,
        "specificData": {
          "Question": "What's your salary expectation?"
        }
      }
    }
  }
}

###

GET  https://localhost:53881/api/v1/jobs/{{JobId}}
Accept: application/json

###

GET  https://localhost:53881/api/v1/jobs?page=1&pageSize=6&sort=title&sortDirection=desc
Accept: application/json

###

Patch  https://localhost:53881/api/v1/jobs/{{JobId}}
Accept: application/json
Content-Type: application/json

{
  "title": "Developer LV2"
}

###

Delete  https://localhost:53881/api/v1/jobs/{{JobId}}
Accept: application/json

###

POST  https://localhost:53881/api/v1/jobs/{{JobId}}/application
Accept: application/json
Content-Type: application/json

{
  "candidateId": "442dd96e-b9c3-440b-9d4b-b38c01676154"
}

###

GET  https://localhost:53881/api/v1/job-applications/jobs/{{JobId}}?page=1&pageSize=5
Accept: application/json

###

GET  https://localhost:53881/api/v1/job-applications/{{JobApplicationId}}
Accept: application/json

###

POST  https://localhost:53881/api/v1/job-applications/{{JobApplicationId}}/answer
Accept: application/json
Content-Type: application/json

{
  "answer": "I don't think that works for me, minimum I can accept is 82k"
}

###

POST  https://localhost:53881/api/v1/job-applications/{{JobApplicationId}}/approve-step
Accept: application/json
Content-Type: application/json

{
  "finalObservations": "budget was approved!"
}

###

POST  https://localhost:53881/api/v1/job-applications/{{JobApplicationId}}/reject-step
Accept: application/json
Content-Type: application/json

{
  "finalObservations": "Candidate asked for a salary above approved budget."
}

###
